### ISSUE TITLE
SingletonApplication.RequestInstance(): Uncaught UnauthorizedAccessException

### ISSUE THREAD

**Issue by spkl** [spkl/CLI.IPC#23]
```
Unhandled Exception: System.UnauthorizedAccessException: Access to the path '[...].lock0' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at spkl.CLI.IPC.Startup.SingletonApplication.IsStarting()
   at spkl.CLI.IPC.Startup.SingletonApplication.RequestInstance()
```

**Comment by spkl** [comment]
When running on .NET Framework, it seems like there are not only IOExceptions that must be caught, but also UnauthorizedAccessExceptions.
